#dit zijn anderson darling test voor alel variabelen voor univariate normality. 
normalityHomeGoals <- ad.test(full_dataset_alan$FTHG)
normalityAwayGoals <- ad.test(full_dataset_alan$FTAG)
normalityHomeYellow <-ad.test(full_dataset_alan$HY) 
normalityAwayYellow <-ad.test(full_dataset_alan$AY)
normalityHomeRed <-ad.test(full_dataset_alan$HR)
normalityAwayRed <-ad.test(full_dataset_alan$AR)
normalityHomeFouls <-ad.test(full_dataset_alan$HF)
normalityAwayFouls <-ad.test(full_dataset_alan$AF)
normalityAwayWin <-ad.test(full_dataset_alan$away_win)
normalityHomeWin<-ad.test(full_dataset_alan$home_win)
normalityHomeShots <-ad.test(full_dataset_alan$HS)
normalityAwayShots <-ad.test(full_dataset_alan$AS)
normalityExpectedGoalsHome <-ad.test( full_dataset_alan$xg1)
normalityExpectedGoalsAway <-ad.test( full_dataset_alan$xg2)
normalityHomePoints <- ad.test( full_dataset_alan$home_points)
normalityAwayPoints <- ad.test(full_dataset_alan$away_points)
normalityPercentagePointsHome <- ad.test( full_dataset_alan$PercentagePointsHome)
normalityPercentagePointsAway <- ad.test( full_dataset_alan$percentage_points_away)
normalityHomeShotsTarget <- ad.test( full_dataset_alan$HST)
normalityAwayShotsTarget <- ad.test( full_dataset_alan$AST)
normalityPointsDifference <- ad.test( full_dataset_alan$PointsDifference)
normalityYellowCardDifference <- ad.test( full_dataset_alan$YellowCardDifference)
normalityRedCardDifference <- ad.test( full_dataset_alan$RedCardDifference)
normalityFoulDifference <- ad.test( full_dataset_alan$FoulDifference)
normalityGoalDifference <- ad.test(full_dataset_alan$GoalDifference)
normalityExpectedGoalsDifference <- ad.test(full_dataset_alan$ExpectedGoalsDifference)
#output, moet helaas per test dus beetje lang werk
output <- pander(normalityHomeGoals)